### ISSUE TITLE
New release every day?

### ISSUE THREAD

**Issue by jonashaag** [sparkfish/shabby-pages#83]
Hi, is some release automation going wrong? It looks like there is a new release every day with no code changes

**Comment by jboarman** [comment]
Hi @jonashaag.   The process has some intentional randomness, so we've used GH's releases to automate validation on a small set of images as way to ensure upstream changes from Augraphy had the intended effect.  (The process also used to post a daily image to Twitter before they broke the API and authentication processes.)

**Comment by jonashaag** [comment]
Do I understand correctly that this works as designed? It makes it impossible to get notified about actual new releases through GH's watch settings.

**Comment by jboarman** [comment]
Shabby is not really maintained as a standalone project.  If you want to watch for updates, Augraphy is more likely what you want to monitor.
